/** Small hand-made content for rule tests, so tuning the real balance data never breaks them. */
import { BalanceSchema, CitySchema, type GameContent, MetaSchema } from '@fastlane/content';

export const fixtureContent: GameContent = {
  meta: MetaSchema.parse({ contentVersion: 1, defaultCity: 'test' }),
  balance: BalanceSchema.parse({
    weekHours: 10,
    statRanges: {
      cash: { min: 0, max: null },
      energy: { min: 0, max: 100 },
      health: { min: 0, max: 100 },
      happiness: { min: 0, max: 100 },
      social: { min: 0, max: 100 },
      creditScore: { min: 300, max: 850 },
      wardrobe: { min: 0, max: 1 },
    },
    startingStats: {
      cash: 20,
      energy: 50,
      health: 50,
      happiness: 50,
      social: 50,
      creditScore: 600,
      wardrobe: 0,
    },
    wardrobeTiers: ['Casual', 'Smart'],
    restBonusEnergyPerHour: 2,
    lowEnergy: { threshold: 20, outputMultiplier: 0.5 },
    hungerPenalty: { energy: -10, health: -5 },
    weeklyDrift: { energy: 20, social: -3 },
  }),
  city: CitySchema.parse({
    id: 'test',
    name: 'Testville',
    board: {
      home: 'a',
      locations: [
        { id: 'a', name: 'A' },
        { id: 'b', name: 'B' },
        { id: 'c', name: 'C' },
        { id: 'd', name: 'D' },
        { id: 'e', name: 'E' },
      ],
      transportModes: [
        {
          id: 'walk',
          name: 'Walk',
          hoursBase: 0,
          hoursPerStep: 1,
          costBase: 0,
          costPerStep: 0,
          energyPerStep: 2,
        },
        {
          id: 'cab',
          name: 'Cab',
          hoursBase: 0.25,
          hoursPerStep: 0.25,
          costBase: 5,
          costPerStep: 1,
          energyPerStep: 0,
        },
        {
          id: 'bike',
          name: 'Bike',
          hoursBase: 0,
          hoursPerStep: 0.5,
          costBase: 0,
          costPerStep: 0,
          energyPerStep: 0,
          requiresItem: 'bike',
        },
      ],
    },
    actions: [
      {
        id: 'rest',
        location: 'a',
        name: 'Rest',
        hours: 2,
        cost: 0,
        effects: { energy: 10 },
        tags: ['rest'],
      },
      {
        id: 'snack',
        location: 'b',
        name: 'Snack',
        hours: 1,
        cost: 4,
        effects: { health: -1 },
        tags: ['eat'],
      },
      {
        id: 'shift',
        location: 'c',
        name: 'Shift',
        hours: 4,
        cost: 0,
        effects: { cash: 40, energy: -15 },
        tags: ['output'],
      },
      {
        id: 'party',
        location: 'b',
        name: 'Party',
        hours: 3,
        cost: 10,
        effects: { social: { min: 2, max: 9 }, energy: -60 },
        tags: ['social'],
      },
      {
        id: 'grind',
        location: 'a',
        name: 'Grind',
        hours: 10,
        cost: 0,
        effects: { cash: { min: 10, max: 30 } },
        tags: ['output'],
      },
    ],
  }),
};
