/** Small hand-made content for rule tests, so tuning the real balance data never breaks them. */
import {
  AiSchema,
  BalanceSchema,
  CitySchema,
  type GameContent,
  MetaSchema,
  NewsSchema,
  QuestSchema,
  WeekendEventSchema,
} from '@fastlane/content';

const work = (id: string, location: string) => ({
  id,
  location,
  kind: 'work-shift',
  minutes: 60,
  durations: [60, 120, 240],
  cost: 0,
  effects: { energy: -2 },
  outputTarget: 'workOutput',
});

export const fixtureContent: GameContent = {
  meta: MetaSchema.parse({ contentVersion: 1, defaultCity: 'test' }),
  balance: BalanceSchema.parse({
    weekMinutes: 600,
    statRanges: {
      cash: { min: 0, max: null },
      energy: { min: 0, max: 100 },
      health: { min: 0, max: 100 },
      happiness: { min: 0, max: 100 },
      social: { min: 0, max: 100 },
      creditScore: { min: 300, max: 850 },
      wardrobe: { min: 0, max: 1 },
    },
    startingStats: {
      cash: 2000,
      energy: 50,
      health: 50,
      happiness: 50,
      social: 50,
      creditScore: 600,
      wardrobe: 0,
    },
    wardrobeTiers: ['casual', 'smart'],
    restBonusEnergyPerHour: 2,
    statModifiers: [
      { id: 'low-energy', stat: 'energy', below: 20, target: 'workOutput', bp: -5000 },
    ],
    hungerPenalty: { energy: -10, health: -5 },
    weeklyDrift: { energy: 20, social: -3 },
    jobs: {
      maxWeeklyMinutes: 360,
      ratingStart: 50,
      ratingPerHour: 5,
      noShowPenalty: 30,
      promotionRating: 60,
    },
    aiDisruption: {
      baseRateBp: 0,
      outcomeWeights: { hoursCut: 1, restructure: 1, layoff: 1 },
      hoursCutBp: -5000,
      minHoursCapBp: 5000,
      restructureWageBp: -2000,
      minWageBp: 5000,
      track: 'tech',
      exposureCutPerPointBp: 1000,
      maxExposureCutBp: 5000,
      outputPerPointBp: 500,
      maxOutputBp: 2000,
    },
    gig: { deactivationChanceBp: 0, deactivationWeeks: 2 },
    skills: { tracks: ['tech', 'craft'], pointsScale: 1 },
    housing: { leaseWeeks: 2, renewalHikeBp: { min: 1000, max: 1000 }, evictAfterMissed: 2 },
    inflation: { weeklyDriftBp: { min: 0, max: 0 }, wageCatchUpBp: 5000 },
    finance: {
      savingsWeeklyPpm: 10_000,
      card: { weeklyPpm: 20_000, limits: [{ minScore: 300, limit: 5000 }] },
      studentWeeklyPpm: 0,
      minPaymentBp: 1000,
      minPayment: 100,
      lateFee: 50,
      collectionsAfter: 2,
      collectionsFee: 200,
      credit: {
        onTime: 1,
        onTimeRent: 1,
        missed: -10,
        collections: -50,
        missedRent: -20,
        eviction: -30,
      },
    },
    market: {
      assets: [{ id: 'fund', crashChanceBp: 0, crashBp: 0 }],
      regimes: [
        {
          id: 'flat',
          weight: 1,
          weeks: { min: 4, max: 4 },
          returnsBp: { fund: { min: 0, max: 0 } },
        },
      ],
      startRegime: 'flat',
    },
    goals: {
      presets: {
        chill: { wealth: 3000, wellbeing: 40, skills: 1, career: 10 },
        standard: { wealth: 100_000, wellbeing: 80, skills: 20, career: 40 },
        'hustle-culture': { wealth: 1_000_000, wellbeing: 95, skills: 50, career: 80 },
      },
      wellbeingLowPartPenaltyBp: 5000,
      careerPointsPerLevel: 20,
      stabilityExposureBp: 5000,
    },
    events: { chanceBp: 10_000, cooldownWeeks: 2 },
    news: { chanceBp: 10_000, maxActive: 1 },
    quests: { active: 1, cooldownWeeks: 2 },
    teasers: { promotionRatingGap: 10, credentialMinutes: 600 },
    rival: { nearMissBp: 9000, netWorthJump: 500, closeBp: 500, quietBp: 300, quietNetWorth: 250 },
  }),
  city: CitySchema.parse({
    id: 'test',
    board: {
      home: 'a',
      locations: [{ id: 'a' }, { id: 'b' }, { id: 'c' }, { id: 'd' }, { id: 'e' }],
      // a→b 1, b→c 1, c→d 1, d→e 1, e→a 2: a to e is 2 either way, a to d is 3 one way and 3 the other.
      segments: [1, 1, 1, 1, 2],
      transportModes: [
        {
          id: 'walk',
          minutesBase: 0,
          minutesPerStep: 60,
          costBase: 0,
          costPerStep: 0,
          energyPerStep: 2,
        },
        {
          id: 'cab',
          minutesBase: 15,
          minutesPerStep: 15,
          costBase: 500,
          costPerStep: 100,
          energyPerStep: 0,
        },
        {
          id: 'bike',
          minutesBase: 0,
          minutesPerStep: 30,
          costBase: 0,
          costPerStep: 0,
          energyPerStep: 0,
          requiresItem: 'bike',
        },
      ],
    },
    gigPayPerHour: { min: 100, max: 300 },
    actions: [
      { id: 'rest', location: 'a', kind: 'basic', minutes: 120, cost: 0, effects: { energy: 10 } },
      { id: 'snack', location: 'b', kind: 'eat', minutes: 60, cost: 400, effects: { health: -1 } },
      {
        id: 'shift',
        location: 'c',
        kind: 'basic',
        minutes: 240,
        cost: 0,
        effects: { cash: 4000, energy: -15 },
        outputTarget: 'workOutput',
      },
      {
        id: 'party',
        location: 'b',
        kind: 'basic',
        minutes: 180,
        cost: 1000,
        effects: { social: { min: 2, max: 9 }, energy: -60 },
      },
      {
        id: 'grind',
        location: 'a',
        kind: 'basic',
        minutes: 600,
        cost: 0,
        effects: { cash: { min: 1000, max: 3000 } },
        outputTarget: 'workOutput',
      },
      work('work-c', 'c'),
      {
        id: 'gig',
        location: '*',
        kind: 'gig',
        minutes: 60,
        durations: [60, 120],
        cost: 0,
        effects: { energy: -1 },
        outputTarget: 'workOutput',
      },
      { id: 'apply', location: 'd', kind: 'apply-job', minutes: 60, cost: 0, effects: {} },
      { id: 'shop', location: 'd', kind: 'buy', minutes: 15, cost: 0, effects: {} },
      { id: 'enroll', location: 'e', kind: 'enroll', minutes: 15, cost: 0, effects: {} },
      { id: 'drop', location: 'e', kind: 'drop-course', minutes: 15, cost: 0, effects: {} },
      {
        id: 'enroll-loan',
        location: 'e',
        kind: 'enroll',
        loan: true,
        minutes: 15,
        cost: 0,
        effects: {},
      },
      {
        id: 'study',
        location: 'e',
        kind: 'study',
        minutes: 60,
        durations: [60, 120],
        cost: 0,
        effects: { energy: -1 },
        outputTarget: 'studyOutput',
      },
      { id: 'lease', location: 'e', kind: 'rent-home', minutes: 15, cost: 0, effects: {} },
      { id: 'cook', location: 'a', kind: 'eat-stored', minutes: 15, cost: 0, effects: {} },
      {
        id: 'host',
        location: 'a',
        kind: 'basic',
        minutes: 60,
        cost: 100,
        effects: { social: 5 },
        requires: { housing: 'flat' },
      },
      { id: 'sub', location: 'a', kind: 'subscribe', minutes: 15, cost: 0, effects: {} },
      { id: 'unsub', location: 'a', kind: 'unsubscribe', minutes: 15, cost: 0, effects: {} },
      { id: 'audit', location: 'a', kind: 'subscription-audit', minutes: 15, cost: 0, effects: {} },
      ...(['deposit', 'withdraw', 'borrow', 'repay'] as const).map((kind) => ({
        id: kind,
        location: 'b',
        kind,
        minutes: 15,
        amounts: [500, 1000],
        cost: 0,
        effects: {},
      })),
    ],
    jobs: [
      {
        id: 'clerk',
        location: 'c',
        ladder: 'office',
        level: 1,
        wage: 600,
        dressTier: 0,
        minExperience: 0,
        requires: { credentials: [], skills: {} },
        aiExposureBp: 5000,
        benefits: { health: false, pto: false },
        remote: false,
        openChanceBp: 10_000,
      },
      {
        id: 'manager',
        location: 'c',
        ladder: 'office',
        level: 2,
        wage: 1200,
        dressTier: 1,
        minExperience: 120,
        requires: { credentials: ['cert'], skills: {} },
        aiExposureBp: 2000,
        benefits: { health: true, pto: true },
        remote: false,
        openChanceBp: 0,
      },
    ],
    courses: [
      {
        id: 'cert',
        type: 'cert',
        track: 'tech',
        tuition: 1000,
        studyMinutes: 120,
        credentialPoints: 10,
        loanEligible: false,
      },
      {
        id: 'degree',
        type: 'degree',
        track: 'craft',
        tuition: 5000,
        studyMinutes: 600,
        credentialPoints: 20,
        loanEligible: true,
      },
    ],
    housing: [
      { id: 'couch', rent: 0, deposit: 0, minCreditScore: 300, weekly: {} },
      { id: 'flat', rent: 300, deposit: 600, minCreditScore: 550, weekly: { happiness: 2 } },
      { id: 'loft', rent: 900, deposit: 1800, minCreditScore: 700, weekly: { happiness: 4 } },
    ],
    items: [
      { id: 'bike', shop: 'd', price: 800, resaleBp: 5000, modifiers: [], weekly: {} },
      { id: 'fridge', shop: 'd', price: 500, resaleBp: 2000, modifiers: [], weekly: {} },
      {
        id: 'food-box',
        shop: 'd',
        price: 300,
        resaleBp: 0,
        modifiers: [],
        weekly: {},
        meals: 3,
        requiresItem: 'fridge',
      },
      {
        id: 'suit',
        shop: 'd',
        price: 400,
        resaleBp: 2500,
        modifiers: [],
        weekly: {},
        wardrobeTier: 1,
      },
      {
        id: 'gadget',
        shop: 'd',
        price: 200,
        resaleBp: 5000,
        modifiers: [{ target: 'workOutput', bp: 1000 }],
        weekly: { happiness: 1 },
      },
    ],
    subscriptions: [
      {
        id: 'stream',
        weeklyCost: 100,
        modifiers: [],
        weekly: { happiness: 1 },
      },
      {
        id: 'meal-kit',
        weeklyCost: 150,
        modifiers: [],
        weekly: {},
        meals: 1,
      },
    ],
  }),
  // No events, news or quests by default, so rule tests see only the rule they test. `hooksContent` adds them.
  events: [],
  news: [],
  quests: [],
  ai: AiSchema.parse({
    utility: {
      buffWeeks: 4,
      energyComfort: 30,
      energyPenalty: 2000,
      cashCushion: 1000,
      liquidityBp: 1000,
      workMinutesPerWeek: 1800,
      stepMinutes: 60,
      futurePayBp: 5000,
      aspirationBp: 6000,
      patienceWeeks: 1,
      prospectBp: 7000,
      overshootBp: 1500,
      valueCapBp: 12_500,
      longerSlackBp: 1500,
    },
    // Off by default: rule tests see a Jones that doesn't react to the score.
    rubberBand: {
      thresholdBp: 10_000,
      spanBp: 1,
      bestMoveDropBp: 0,
      runnersUpExtra: 0,
      riskShiftBp: 0,
      catchUpBp: 0,
    },
    rivals: [
      {
        id: 'jones',
        goalWeightsBp: { wealth: 2500, wellbeing: 2500, skills: 2500, career: 2500 },
        bottleneckBp: 5000,
        riskAppetiteBp: 5000,
        horizonWeeks: 4,
        bestMoveRateBp: 10_000,
        runnersUp: 1,
        notes: 'Test rival',
      },
      {
        id: 'jones-sloppy',
        goalWeightsBp: { wealth: 2500, wellbeing: 2500, skills: 2500, career: 2500 },
        bottleneckBp: 5000,
        riskAppetiteBp: 5000,
        horizonWeeks: 4,
        bestMoveRateBp: 0,
        runnersUp: 3,
        notes: 'Never takes the best move',
      },
    ],
    byDifficulty: { chill: 'jones-sloppy', standard: 'jones', 'hustle-culture': 'jones' },
  }),
};

/** Fixture content with a small event deck, news and quests, for the Phase 3 hooks. */
export const hooksContent: GameContent = {
  ...fixtureContent,
  events: WeekendEventSchema.array().parse([
    {
      id: 'windfall',
      category: 'money',
      weight: 1,
      choices: [{ id: 'take', effects: { cash: { min: 100, max: 200 }, happiness: 2 } }],
    },
    {
      id: 'dilemma',
      category: 'life',
      weight: 1,
      choices: [
        { id: 'splurge', cost: 300, effects: { happiness: 10 }, nextWeekMinutes: -60 },
        { id: 'save', effects: { happiness: -2 } },
        { id: 'bike-ride', effects: { health: 5 }, when: { items: ['bike'] } },
      ],
    },
    {
      id: 'boss',
      category: 'work',
      weight: 1,
      when: { job: true },
      choices: [{ id: 'cope', effects: { happiness: -1 }, jobRating: -10, layoffWarning: true }],
    },
    {
      id: 'crash',
      category: 'health',
      weight: 1,
      trigger: 'burnout',
      cooldownWeeks: 0,
      choices: [{ id: 'rest', effects: { energy: 20 }, nextWeekMinutes: -120 }],
    },
  ]),
  news: NewsSchema.array().parse([
    {
      id: 'surge',
      weight: 1,
      weeks: { min: 2, max: 2 },
      effects: { gigPayBp: 5000, disruptionBp: 10_000, rentHikeBp: 1000 },
    },
  ]),
  quests: QuestSchema.array().parse([
    {
      id: 'get-hired',
      weight: 1,
      weeks: 2,
      when: { job: false },
      goal: { kind: 'hired' },
      reward: { cash: 50 },
    },
    {
      id: 'save-up',
      weight: 1,
      weeks: 3,
      goal: { kind: 'save', amount: 500 },
      reward: { stats: { happiness: 5 } },
    },
  ]),
};
